X-INCLUDE:
  - templates/core.yml
  - templates/image_version.yml
  - templates/traefik.yml
X-OUTPUT: services/traefik.yml
X-OVERRIDE:
  X-REF-TRAEFIK-CONTAINER: ${TRAEFIK_CONTAINER:?}
  X-REF-TRAEFIK-ENV:
    - CF_DNS_API_TOKEN_FILE=/run/secrets/cf_api_token
  X-REF-TRAEFIK-PORTS:
    - ${TRAEFIK_HTTPS_PORT:?}:443
  X-REF-TRAEFIK-VOLUME:
    - ${TRAEFIK_DATA:?}/dynamic_config.yml:/etc/traefik/dynamic_config.yml
    - ${TRAEFIK_DATA:?}/static_config.yml:/etc/traefik/traefik.yml:ro
    - ${TRAEFIK_DATA:?}/acme.json:/acme.json

services:
  traefik:
    X-REF-FUNCT-TEMPLATE-TRAEFIK(X-REF-TRAEFIK-CONTAINER,X-REF-TRAEFIK-ENV,X-REF-TRAEFIK-PORTS,X-REF-TRAEFIK-VOLUME):
    secrets:
      - cf_api_token
    networks:
      - traefik_network
networks:
  traefik_network:

secrets:
  cf_api_token:
    file: ${TRAEFIK_CF_TOKEN_FILE:?}
