services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    restart: always
    environment:
      - VPN_SERVICE_PROVIDER=${ARR_VPN_SERVICE_PROVIDER:?}
      - VPN_TYPE=${ARR_VPN_TYPE:?}
      - SERVER_COUNTRIES=${ARR_SERVER_COUNTRIES:?}
      - VPN_PORT_FORWARDING_PROVIDER=${ARR_VPN_PORT_FORWARDING_PROVIDER:?}
      - UPDATE_PERIOD=${ARR_VPN_UPDATE_PERIOD:?}
      - WIREGUARD_PRIVATE_KEY=${ARR_WIREGUARD_PRIVATE_KEY:?}
    ports:
      - 7878:7878
      - 8080:8080
      - 9696:9696
      - 8989:8989
    networks:
      - arr_stack_network
    cap_add:
      - NET_ADMIN
    devices:
      - ${ARR_GLUETUN_TUN_DEVICE:?}:/dev/net/tun
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    mem_limit: 512m
    cpus: "1.0"
  prowlarr:
    profiles:
      - all
      - arr_stack
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ${ARR_PROWLARR_CONFIG_PATH:?}:/config
      - ${ARR_DATA_PATH:?}:/data
    depends_on:
      - gluetun
    network_mode: service:${ARR_GLUETUN_SERVICE_NAME:?}
    mem_limit: 512m
    pids_limit: 100
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
  radarr:
    profiles:
      - all
      - arr_stack
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ${ARR_RADARR_CONFIG_PATH:?}:/config
      - ${ARR_DATA_PATH:?}:/data
    depends_on:
      - gluetun
    network_mode: service:${ARR_GLUETUN_SERVICE_NAME:?}
    mem_limit: 512m
    pids_limit: 100
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
  sonarr:
    profiles:
      - all
      - arr_stack
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
    volumes:
      - ${ARR_SONARR_CONFIG_PATH:?}:/config
      - ${ARR_DATA_PATH:?}:/data
    depends_on:
      - gluetun
    network_mode: service:${ARR_GLUETUN_SERVICE_NAME:?}
    mem_limit: 512m
    pids_limit: 100
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
  qbittorrent:
    profiles:
      - all
      - arr_stack
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Singapore
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${ARR_QBITTORRENT_CONFIG_PATH:?}:/config
      - ${ARR_DATA_PATH:?}:/data
    depends_on:
      - gluetun
    network_mode: service:${ARR_GLUETUN_SERVICE_NAME:?}
    mem_limit: 1g
    pids_limit: 100
    cpus: "1.0"
    security_opt:
      - no-new-privileges:true
networks:
  arr_stack_network:
    name: arr_stack_network
    external: true
