services:
  cloudflared:
    profiles:
      - all
      - cloudflare
    image: cloudflare/cloudflared:2026.5.1
    container_name: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
      - --token-file
      - /run/secrets/cf_token
    restart: unless-stopped
    environment:
      - TZ=Asia/Singapore
    networks:
      - traefik_network
    secrets:
      - cf_token
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    mem_limit: 512m
    cpus: "1.0"
networks:
  traefik_network:
    external: true
secrets:
  cf_token:
    file: ${TRAEFIK_CF_TOKEN_FILE:?}
